### ISSUE TITLE
KeyError: 9437184

### ISSUE THREAD

**Issue by zhaocai** [shawnrice/alfred2-workflow-help#1]
> python help.py 

Traceback (most recent call last):
  File "help.py", line 189, in <module>
    hotkeys += "\r\n\* " + hotmod[item['config']['hotmod']] + " " + item['config']['hotstring']
KeyError: 9437184

**Comment by shawnrice** [comment]
Which hotkeys have you assigned to those?

**Comment by shawnrice** [comment]
So, it seems that Alfred might have changed a few of the values for the hotkey modifiers, and so I think that you have a legacy value. We saw the same problem in another place, and clintxs put in a pull request for the change (https://github.com/shawnrice/alfred2-workflow-help/pull/2). Grab the updated copy, and see if that fixes your problem.
