### ISSUE TITLE
Does not seem to work on Yosemite

### ISSUE THREAD

**Issue by Geordon** [shawnrice/alfred2-workflow-help#6]
I've left the script running (assuming that it would need some time to complete) for at least a half an hour but all that I have to show for it is a qlmanage icon in my Dock.

```
ps -ef|grep ql
  501 94838     1   0 10:07PM ??         0:00.32 qlmanage -p /Users/gvantass/Library/Application Support/Alfred 2/Workflow Data/com.help.shawn.rice/alfred-help.md -c .md -g libraries/QLMarkdown.qlgenerator
```

Any ideas?

**Comment by shawnrice** [comment]
Yeah, someone pointed that out. I've been meaning to do a full rewrite. As a temporary fix, I did put up a version that works (https://github.com/shawnrice/alfred2-workflow-help/blob/master/whw.alfredworkflow). It doesn't use `qlmanage` right now but instead just opens a window in your browser. There is quite a bit more to do, but I need to find some time to do it.

Look at the [forums thread](http://www.alfredforum.com/topic/1653-workflows-help-workflow/page-3) for a better explanation.
