### ISSUE TITLE
Download link doesn't work.

### ISSUE THREAD

**Issue by zevaverbach** [shawnrice/alfred2-workflow-help#7]
Shawn-- I'm excited to try this.  

P.s. the "donate" button is not working on Packal --> "Sorry — your last action could not be completed" is displayed just after pressing "send" on my donation.

**Comment by shawnrice** [comment]
The download link that doesn't work is the one on Packal? Or one here?

The old version — the one that is on Packal — doesn't work on Yosemite. I've put up a temporary version in this repo here: https://github.com/shawnrice/alfred2-workflow-help/raw/master/whw.alfredworkflow (direct link). It has a different bundle id than the normal one, so it won't be upgraded when I finally find the time to finish the rewrite.

That's strange about the Paypal link. It should be working. When I click on it, it does come up with the correct email address. If you're interested in trying again, then maybe just try it again. It might have been a strange, momentary thing with Paypal.

**Comment by zevaverbach** [comment]
The one here -- https://github.com/shawnrice/alfred2-workflow-help -- both links are dead, FYI.

Thanks for the link, and for all the work you do, Shawn.  I will try the Paypal again...

Zev Averbach
Averbach Transcription
(212) 392-0149
www.avtranscription.com

On Thu, Dec 4th, 2014 at 04:54 AM notifications@github.com  wrote :
